# Generated by Django 6.0.2 on 2026-03-06 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('diseno', 'Diseño Gráfico'), ('desarrollo', 'Desarrollo Web'), ('marketing', 'Marketing Digital'), ('redaccion', 'Redacción'), ('video', 'Video y Animación'), ('otro', 'Otro')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_entrega', models.CharField(max_length=50)),
                ('incluye', models.JSONField(blank=True, default=list)),
                ('imagen_url', models.URLField(blank=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('cerrado', 'Cerrado')], default='borrador', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estado', '-created_at'], name='publicacion_estado_8c562d_idx'), models.Index(fields=['categoria'], name='publicacion_categor_de198b_idx')],
            },
        ),
    ]
