# Generated by Django 6.0.2 on 2026-03-15 01:12

import django.db.models.deletion
import publicaciones.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPublicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to=publicaciones.models.imagen_upload_path)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='publicaciones.publicacion')),
            ],
            options={
                'verbose_name': 'Imagen de Publicación',
                'verbose_name_plural': 'Imágenes de Publicación',
                'ordering': ['orden'],
            },
        ),
    ]
