# Generated by Django 6.0.2 on 2026-04-19 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_imagenpublicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='imagen_url',
        ),
    ]
