# Generated by Django 6.0.2 on 2026-05-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_review'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_per_contract_reviewer',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
